#NOTE: DO NOT INCLUDE "/" AT THE END OF PATHS!!!
paths:
    CONCOCT: /c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/temp/repos/CONCOCT
    CONCOCT_TEST: /c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/temp/CONCOCT-test-data-0.3.2
    raw_reads: /c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/binning/perSamplePipe/reads
    concoct_run: /c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/binning/perSamplePipe

megahit_params:
    threads: 64

cutcontigs_params:
    script_dir: /c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/temp/repos/CONCOCT/scripts/cut_up_fasta.py

kallisto_params:
    threads: 64
    script: /c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/kallisto2concoctTable.py

concoct_params:
    clusters: 2000
    threads: 64

checkM_params:
    threads: 64

carveme_params:
    dir: carvemeOut
    cutoff: 100k

                              #BELOW ARE PARAMS FOR RULES NO LONGER USED

#bowtie_params:
#    MRKDUP_jardir: /c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/.conda/envs/concoct_env/share/picard-2.18.4-0/MarkDuplicates.jar
#    MRKDUP_shelldir: /c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/temp/repos/CONCOCT/scripts/map-bowtie2-markduplicates.sh
#    threads: 8

#speciesProt_params:
#    newline: \n
#    tab: \t
#    dir: speciesProt
#    scriptdir: /c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/binning/
#    infile: clustering_gt1000_scg.tab
#    pFASTA: ../annotations/proteins/megahit_c10K.faa
#    pFASTAcleanID: cleanID.faa

#speciesDNA_params:
#    dir: speciesDNA
#    cutoff: 300k
#    FASTAcleanID: cleanID.fa
#    FASTA: ../contigs/megahit_c10K.fa

#old concoct PARAMS
    #cutoptions: -f1,3-
    #covfile: concoct-input/concoct_inputtableR.tsv
    #compositionfile: contigs/megahit_c10K.fa
    #outputdir: concoct-output/
