path:
    root: /scratch/zorrilla/tara
folder:
    data: dataset
    logs: logs
    assemblies: assemblies
    scripts: scripts
    crossMap: crossMap 
    concoct: concoct
    maxbin: maxbin
    metabat: metabat
    refined: refined_bins
    reassembled: reassembled_bins
    classification: classification
    abundance: abundance
    GRiD: GRiD
    GEMs: GEMs
    SMETANA: SMETANA
    memote: memote
    qfiltered: qfiltered
    stats: stats
    proteinBins: protein_bins
    dnaBins: dna_bins
    pangenome: pangenome
scripts:
    kallisto2concoct: kallisto2concoct.py
    prepRoary: prepareRoaryInput.R
    binFilter: binFilter.py
    qfilterVis: qfilterVis.R
    assemblyVis: assemblyVis.R
    binningVis: binningVis.R
    modelVis: modelVis.R
    abundanceVis: abundanceVis.R
    taxonomyVis: taxonomyVis.R
    carveme: media_db.tsv
    toy: download_toydata.txt
    GTDBtkVis: 
cores:
    fastp: 4
    megahit: 48
    crossMap: 48
    concoct: 48
    metabat: 48
    maxbin: 48
    refine: 48
    reassemble: 48
    classify: 2
    gtdbtk: 48
    abundance: 16
    carveme: 4
    smetana: 12
    memote: 4
    grid: 24
    prokka: 2
    roary: 12
params:
    cutfasta: 10000
    assemblyPreset: meta-sensitive
    assemblyMin: 1000
    concoct: 800
    metabatMin: 50000
    seed: 420
    minBin: 1500
    refineMem: 1600
    refineComp: 50
    refineCont: 10
    reassembleMem: 1600
    reassembleComp: 50
    reassembleCont: 10
    carveMedia: M8
    smetanaMedia: M1,M2,M3,M4,M5,M7,M8,M9,M10,M11,M13,M14,M15A,M15B,M16
    smetanaSolver: CPLEX
    roaryI: 90
    roaryCD: 90
envs:
    metabagpipes: metabagpipesFinal
    metawrap: metawrap
    
