path:
    root: /path/to/workspace
folder:
    data: dataset
    logs: logs
    assemblies: assemblies
    scripts: scripts
    concoct: concoct
    maxbin: maxbin
    metabat: metabat
    refined: refined_bins
    reassembled: reassembled_bins
    classification: classification
    abundance: abundance
    GRiD: GRiD
    GEMs: GEMs
    SMETANA: SMETANA
    memote: memote
    qfiltered: qfiltered
    stats: stats
    finalBins: final_bins
scripts:
    kallisto2concoct: kallisto2concoct.py
    binFilter: binFilter.py
    qfilterVis: qfilterVis.R
    assemblyVis: assemblyVis.R
    binningVis: binningVis.R
    modelVis: modelVis.R
    taxonomyVis: taxonomyVis.R
    carveme: media_db.tsv
    toy: download_toydata.txt
cores:
    fastp: 4
    megahit: 24
    crossMap: 24
    concoct: 24
    metabat: 24
    maxbin: 24
    refine: 24
    reassemble: 24
    classify: 2
    abundance: 16
    carveme: 4
    smetana: 12
    memote: 4
    grid: 24
params:
    cutfasta: 10000
    assemblyPreset: meta-sensitive
    concoct: 800
    refineMem: 1600
    refineComp: 50
    refineCont: 10
    reassembleMem: 1600
    reassembleComp: 50
    reassembleCont: 10
    carveMedia: M8
    smetanaMedia: M1,M2,M3,M4,M5,M7,M8,M9,M10,M11,M13,M14,M15A,M15B,M16
    smetanaSolver: CPLEX
envs:
    metabagpipes: metabagpipes
    metawrap: metawrap
    
