path:
    root: /home/zorrilla/workspace/githubReadmeTutorial
folder:
    data: dataset
    logs: logs
    assemblies: assemblies
    scripts: scripts
    concoctInput: concoct_input
    concoctOutput: concoct_output
    maxbin: maxbin_output
    metabat: metabat_output
    refined: refined_bins
    reassembled: reassembled_bins
    classification: classification
    abundance: abundance
    GRiD: GRiD
    GEMs: GEMs
    SMETANA: SMETANA
    memote: memote
scripts:
    kallisto2concoct: /home/zorrilla/workspace/tutorial/scripts/kallisto2concoct.py
    binFilter: /home/zorrilla/workspace/tutorial/scripts/binFilter.py
dbs:
    carveme: /home/zorrilla/workspace/tutorial/scripts/media_db.tsv
    toy: /home/zorrilla/workspace/tutorial/scripts/download_toydata.txt
cores:
    metaspades: 24
    kallisto: 24
    concoct: 24
    metabat: 24
    maxbin: 24
    refine: 24
    reassemble: 24
    classify: 2
    abundance: 16
    carveme: 4
    smetana: 12
    memote: 4
    grid: 24